name: ç¼–è¯‘OPPO/Realme-sm8250æœºå‹å†…æ ¸
            æ”¯æŒksu

on:
  workflow_dispatch:

jobs:
  Set-repos:
    name: "ğŸ‚ Parse repos.json"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
      builddate: ${{ steps.generate-builddate.outputs.builddate }}
    steps:
      - name: "ğŸ˜„ Checkout"
        uses: actions/checkout@v4

      - name: "ğŸ˜† Generate Matrix"
        id: generate-matrix
        run: |
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          jq -s '[.[][]]' repos/repos*.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: "â° Set builddate"
        id: generate-builddate
        run: echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  Build-Kernel:
    name: "build-kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      max-parallel: 7
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      WORKSPACE: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v3

    - name: æ„å»ºç¼–è¯‘å†…æ ¸ç¯å¢ƒ
      run: |
        sudo apt-get update
        sudo -E apt-get -y -qq install git make bc bison ccache openssl dos2unix zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler ca-certificates python3 python2 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace



    - name: ä¸‹è½½ Gccç¼–è¯‘å™¨
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        
        mkdir gcc64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc64/ -zxvf gcc-aarch64.tar.gz
    
        mkdir gcc32
        wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc32/ -zxvf gcc-arm.tar.gz
    - name: ä¸‹è½½java-22.0.1
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        wget https://download.oracle.com/java/22/archive/jdk-22.0.1_linux-x64_bin.tar.gz
        tar -xvf jdk-22.0.1_linux-x64_bin.tar.gz
        
    - name: ä¸‹è½½Clangç¼–è¯‘å™¨
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang-aosp
        git clone -q --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078 -b 10.0 clang-aosp
    
    
    - name: ä¸‹è½½å†…æ ¸æºç 
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/Blackmanx/bigshot_kernel_realme_sm8250 bigshot-215-RUI
        cd bigshot-215-RUI



    - name: æ›´æ–° ksu
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/bigshot-215-RUI
        rm -rf KernelSU
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
        
        
    - name: ä¿®æ”¹sm8250_defconfig
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/bigshot-215-RUI
        sed -i '/^CONFIG_MODULE_SIG/s/^/#/' $GITHUB_WORKSPACE/kernel_workspace/bigshot-215-RUI/arch/arm64/configs/vendor/sm8250_defconfig
               
    - name: è®¾ç½®ccacheç¼“å­˜
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-mido-kernel
        max-size: 2G

 
    - name: å¼€å§‹ç¼–è¯‘å†…æ ¸
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/bigshot-215-RUI
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc64/bin:$GITHUB_WORKSPACE/kernel_workspace/gcc32/bin:$PATH
        export KBUILD_BUILD_HOST=
        export KBUILD_BUILD_USER=
        make -s -j$(nproc --all) O=out ARCH=arm64 vendor/sm8250_defconfig
        make -j$(nproc --all) CC="ccache clang" O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- LD=ld.lld
                

    - name: åˆ¶ä½œAnykernel3å¡åˆ·åŒ…
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/osm0sis/AnyKernel3
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
        sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
        sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
        cp android-kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        
    
    
    - name: ä¸Šä¼  Anykernel3
      uses: actions/upload-artifact@v3
      with:
        name: å†…æ ¸-å¡åˆ·åŒ…
        path: kernel_workspace/AnyKernel3/*
        

    - name: ä¸Šä¼ ç¼–è¯‘å†…æ ¸
      uses: actions/upload-artifact@v3
      with:
        name: sm8250-Image.gz
        path: kernel_workspace/bigshot-215-RUI/out/arch/arm64/boot/Image.gz